config/routes.rb
Anonymity::Application.routes.draw do
  
  devise_for :admins

  root :to => 'articles#index'

  resources :comments

  resources :matters

  resources :articles

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

			#can :manage, :all
			can :read, :all
			can :create, Comment
			can :create, Matter

		unless user.nil?
			can :manage, :all
  	end 


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/article.rb
class Article < ActiveRecord::Base

has_many :matters

end

app/models/comment.rb
class Comment < ActiveRecord::Base

belongs_to :matter

end

app/models/matter.rb
class Matter < ActiveRecord::Base

has_many :comments
belongs_to :article

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	#before_filter :authenticate_admin!
  protect_from_forgery

	def current_ability
  @current_ability ||= Ability.new(current_admin)
end

	rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	load_and_authorize_resource

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :ok }
    end
  end
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController

	load_and_authorize_resource

  # GET /matters
  # GET /matters.json
  def index
    @matters = Matter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matters }
    end
  end

  # GET /matters/1
  # GET /matters/1.json
  def show
    @matter = Matter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @matter }
    end
  end

  # GET /matters/new
  # GET /matters/new.json
  def new
    @matter = Matter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @matter }
    end
  end

  # GET /matters/1/edit
  def edit
    @matter = Matter.find(params[:id])
  end

  # POST /matters
  # POST /matters.json
  def create
    @matter = Matter.new(params[:matter])

    respond_to do |format|
      if @matter.save
        format.html { redirect_to @matter, notice: 'Matter was successfully created.' }
        format.json { render json: @matter, status: :created, location: @matter }
      else
        format.html { render action: "new" }
        format.json { render json: @matter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matters/1
  # PUT /matters/1.json
  def update
    @matter = Matter.find(params[:id])

    respond_to do |format|
      if @matter.update_attributes(params[:matter])
        format.html { redirect_to @matter, notice: 'Matter was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @matter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matters/1
  # DELETE /matters/1.json
  def destroy
    @matter = Matter.find(params[:id])
    @matter.destroy

    respond_to do |format|
      format.html { redirect_to matters_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.content %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Content:</b>
  <%= @article.content %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :matter_id %><br />
    <%= f.number_field :matter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>E-mail</th>
    <th>Ip</th>
    <th>Content</th>
    <th>Matter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.email %></td>
    <td><%= comment.ip %></td>
    <td><%= comment.content %></td>
    <td><%= comment.matter_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>E-mail:</b>
  <%= @comment.email %>
</p>

<p>
  <b>Ip:</b>
  <%= @comment.ip %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>Matter:</b>
  <%= @comment.matter_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anonymity</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
	<% if admin_signed_in? %>
		<p>Zalogowany jako <%= current_admin.email %></p>
		<p><%= link_to("Logout", destroy_admin_session_path, :method => :delete) %></p>
	<% else %>
		<p>Niezalogowany | <%= link_to("Zaloguj", new_admin_session_path) %></p>
	<% end %>
</div>

<%= yield %>

</body>
</html>

app/views/matters/_form.html.erb
<%= form_for(@matter) do |f| %>
  <% if @matter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@matter.errors.count, "error") %> prohibited this matter from being saved:</h2>

      <ul>
      <% @matter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :article_id %><br />
    <%= f.number_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matters/edit.html.erb
<h1>Editing matter</h1>

<%= render 'form' %>

<%= link_to 'Show', @matter %> |
<%= link_to 'Back', matters_path %>

app/views/matters/index.html.erb
<h1>Listing matters</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Article</th>
    <th>Name</th>
    <th>Ip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matters.each do |matter| %>
  <tr>
    <td><%= matter.title %></td>
    <td><%= matter.description %></td>
    <td><%= matter.article_id %></td>
    <td><%= matter.name %></td>
    <td><%= matter.ip %></td>
    <td><%= link_to 'Show', matter %></td>
    <td><%= link_to 'Edit', edit_matter_path(matter) %></td>
    <td><%= link_to 'Destroy', matter, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Matter', new_matter_path %>

app/views/matters/new.html.erb
<h1>New matter</h1>

<%= render 'form' %>

<%= link_to 'Back', matters_path %>

app/views/matters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @matter.title %>
</p>

<p>
  <b>Description:</b>
  <%= @matter.description %>
</p>

<p>
  <b>Article:</b>
  <%= @matter.article_id %>
</p>

<p>
  <b>Name:</b>
  <%= @matter.name %>
</p>

<p>
  <b>Ip:</b>
  <%= @matter.ip %>
</p>


<%= link_to 'Edit', edit_matter_path(@matter) %> |
<%= link_to 'Back', matters_path %>